### ISSUE TITLE
create multiple functions instead of monolith api

### ISSUE THREAD

**Issue by kukuandroid** [rdlabo-team/serverless-nestjs#19]
Hi, can you assist me on how to create multiple functions instead of monolith api? Thanks

**Comment by rdlabo** [comment]
You can create any index.ts (serverlessframework endppoint).
Like this:

```yml
  hours:
    handler: dist/src/query/hours/index.handler
    events:
      - schedule: cron(0 23,0-11 * * ? *)
```
